const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..', '..')

function read(file) {
  return fs.readFileSync(path.join(root, file), 'utf8')
}

test('docker env configuration @eval(EVAL-PLATFORM-DOCKER-002)', () => {
  const envExample = read('.env.example')
  const readme = read('README.md')
  const config = read('shared/shared-config/src/index.ts')
  const dockerfile = read('.devcontainer/Dockerfile')
  const devcontainer = read('.devcontainer/devcontainer.json')
  const opencodeConfig = read('opencode.json')

  assert.ok(envExample.includes('DATABASE_URL='))
  assert.ok(envExample.includes('SUPABASE_URL='))
  assert.ok(envExample.includes('SUPABASE_SERVICE_ROLE_KEY='))
  assert.ok(envExample.includes('GRAPHQL_ENDPOINT='))
  assert.ok(envExample.includes('VITE_GRAPHQL_ENDPOINT='))
  assert.ok(envExample.includes('EXPO_PUBLIC_GRAPHQL_ENDPOINT='))
  assert.ok(envExample.includes('STRIPE_SECRET_KEY='))
  assert.ok(envExample.includes('STRIPE_PUBLISHABLE_KEY='))
  assert.ok(envExample.includes('STRIPE_WEBHOOK_SECRET='))
  assert.ok(envExample.includes('STRIPE_CLI_WEBHOOK_AUTOSTART=1'))
  assert.ok(readme.includes('pnpm db:up'))
  assert.ok(readme.includes('pnpm dev'))
  assert.ok(readme.includes('Supabase'))
  assert.ok(readme.includes('Dev container (recommended)'))
  assert.ok(readme.includes('pnpm verify:setup'))
  assert.ok(readme.includes('.env.example'))
  assert.ok(readme.includes('.env.local'))
  assert.ok(readme.includes('EXPO_PUBLIC_GRAPHQL_ENDPOINT'))
  assert.ok(readme.includes('STRIPE_CLI_WEBHOOK_AUTOSTART'))
  assert.ok(readme.includes('Stripe test-mode credentials'))
  assert.ok(
    readme.includes('Stripe CLI is preinstalled in the devcontainer image'),
  )
  assert.ok(readme.includes('stripe login'))
  assert.ok(readme.includes('AGENTS.md'))
  assert.ok(readme.includes('opencode.json'))
  assert.ok(readme.includes('architecture/opencode-governance.md'))
  assert.ok(!readme.includes('.opencode/session-backups/'))
  assert.ok(!readme.includes('devcontainer-sync-opencode-sessions.mjs'))
  assert.ok(config.includes('GRAPHQL_ENDPOINT'))
  assert.ok(config.includes('VITE_GRAPHQL_ENDPOINT'))
  assert.ok(dockerfile.includes('ARG STRIPE_CLI_VERSION='))
  assert.ok(dockerfile.includes('/usr/local/bin/stripe --version'))
  assert.ok(dockerfile.includes('/usr/local/bin/uvx --version'))
  assert.ok(devcontainer.includes('stripe --version'))
  assert.ok(
    !devcontainer.includes('scripts/devcontainer-sync-opencode-sessions.mjs'),
  )
  assert.ok(!devcontainer.includes('/.config/opencode'))
  assert.ok(devcontainer.includes('/home/node/.local/share/opencode/auth.json'))
  assert.ok(devcontainer.includes('/home/node/.local/state/opencode'))
  assert.ok(opencodeConfig.includes('"instructions": [".opencode/rules/*.md"]'))
  assert.ok(opencodeConfig.includes('"context7"'))
  assert.ok(opencodeConfig.includes('"gh_grep"'))
  assert.ok(opencodeConfig.includes('"playwright"'))
  assert.ok(opencodeConfig.includes('"code-index"'))
})
